# using both c and python. different python versions used on docker image.
language: minimal

# ubuntu bionic (18.04)
os: linux
dist: bionic

# environment (just for docker, build both x86_64 and i686)
env:
  global:
    - DOCKER_MNT=/_build
  jobs:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PLAT=manylinux1_i686

# pre-install updates
#before_install: bash travis/before_install.sh

# require manylinux1 docker image
install: docker pull $DOCKER_IMAGE

# build on manylinux1 docker images and run tests
script:
  # run script to build wheels on manylinux docker image. note we use bash so
  # that we don't need to make the script executable.
  - >
    docker container run -e PLAT=$PLAT -e DOCKER_MNT=$DOCKER_MNT
    -v `pwd`:$DOCKER_MNT $DOCKER_IMAGE bash $DOCKER_MNT/travis/build_dist.sh
  # for each python version, create venv on docker, run pytest, and
  - >
    docker container run --rm -e PLAT=$PLAT -e DOCKER_MNT=$DOCKER_MNT
    -v `pwd`:$DOCKER_MNT $DOCKER_IMAGE bash $DOCKER_MNT/travis/runt_tests.sh

# conditionally deploy based on DEPLOY_DRY and DEPLOY_WET tags. note that
# PYPI_TOKEN and TESTPYPI_TOKEN are defined in travis. skip cleanup.
deploy:
  provider: script
  script: bash travis/upload_dist.sh
  skip_cleanup: true