language: python

# test a few python versions
python:
  - 3.6
  - 3.7
  - 3.8

# ubuntu bionic (18.04)
os: linux
dist: bionic

# environment (just for docker, build both x86_64 and i686)
env:
  global:
    - DOCKER_MNT=/_build
  jobs:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PLAT=manylinux1_i686

# pre-install updates
before_install: bash travis/before_install.sh

# require numpy, scipy, and manylinux1 docker image (per env line)
install:
  - pip3 install -r travis/requirements.txt
  - docker pull $DOCKER_IMAGE

# build and run tests
script:
  # script can't be sourced so use new shell. builds locally on travis.
  - bash travis/build_local.sh
  # run tests and test setuptools-created scripts after installing package 
  - bash travis/run_tests.sh
  # conditionally deploy based on DEPLOY_DRY and DEPLOY_WET tags. note that
  # PYPI_TOKEN and TESTPYPI_TOKEN are defined in travis. will build source and
  # wheels on manylinux1 docker image
  - bash travis/upload_dist.sh