language: python

# test a few python versions
python:
  - 3.6
  - 3.7
  - 3.8

# ubuntu bionic (18.04)
os: linux
dist: bionic

# pre-install updates
before_install: bash travis/before_install.sh

# depends on numpy and scipy
install:
  - pip3 install --upgrade numpy
  - pip3 install --upgrade scipy

# build and run tests
script:
  # script can't be sourced so use new shell
  - bash travis/build_ext.sh
  # run tests
  - pytest

# conditional deployment
deploy:
  # deploy to test pypi index only if DEPLOY_DRY file is present
  - provider: pypi
    username: __token__
    password:
      secure: Ai7atsDoxe3F8fw2enkCelumS1S4cQwGUsgxBRfxGLYygtmGagdhwPB/V+7W5RRdUeVEU2sb9gOFuf/u0iVa751A4GhjSUj9pss4OZlEJ+zdTnoDx5k4IkDc98GaczFr0W6qrIHCr39QGx//xAEyCxa0wAkp+9C3LF8vfvKvQodITU7IV35BLFcmR8Mk9FQ42Cr8dlVk8MIo5BNK3vddpA4s4hbqCqJzRqzZMjmNIbfRg7j+FkzjX+0Us1mZEqxDSztrmAb2ZR3KyjTchEDw16d/Bk7TVdCj3UWFo8a5c67oHcXcrowEldAMEOt175lXswJCEm/VaNtMoy7uwbPWdAJLZT/iD9rQ63JewCCCX9xsg1jxivVH+1PqxlxtR6IoGq90f3dhbjne2eiH++S0n4bVELnwtKOxr0YWAFTRgGP7PcJtN18Ct26Br5qKM3zmLkPo0ugKNM6jHApmv/mWwEUXs02Vi8VBkk9sgiHGgrmqx9EiXse3iM53qTuV57tR0bvUefL5Nys8x0v7f8e1wm1JYes2b3ve9EsyaYJIW76LX5n3eE49H1pevj02bczThCxUYPm7R3w7AgbBTUd19dIVRLj1z4B65WjZkDIkqSMgI32k8Wa8GhPhiuIsYocK5i9c68eXTWst9HBBL+JCaco5j7o16NDfyk11LCaxehY=
    server: https://test.pypi.org/legacy/
    distributions: sdist
    skip_existing: true
    on:
      condition: -e DEPLOY_DRY
  # deploy to actual pypi index only if DEPLOY_WET file is present
  - provider: pypi
    username: __token__
    password:
      secure: FBDd9eOM+egFuQpCyK4i2b0OZGLk6C4Qvrnnwn0Qt5bkAJjdRdJpB9MzUMy8DRS04LNkBsVCijkS3x1qdHwIOXnwpUrKsXGfsyxTizBuUpMwXYrIC9Pz94o6Zk2Q5J1mh4jCp9Dxih27ceGoulagIfHKargVF53xwF4VUtOgAxeFtulFpRDV9kUKTwpTTxi14P05vCtAA4y+4ShWam8lSIhC1rLBOoDICr9rDCtWCuNuLDozTdrPrslcqKaICvmmfkS6Emu8iZzmFg978sIA8cRgEb6X3CAlqcoUwEbECLH9gCz44iGo2GGCScR15sSkPNWV5gCmaiz89vvkh4ICQ92Dm4njPjBuhPh9LY3nmqCR7/yco34kLQvcZGpcQoRArB4W0lSy/Wb92cnk9+eyJtnZHxh8wBxFT+REQyKqixjczWr1frL++txZvBDUbhw6FhLQWD30g4feGJ9QWdRMSEy5MPUk2iCk9ovTZKEk1e2y9XaqDmNDoii77/0bPOQmRpRLD7NtDLnWlFRqqjhHaScpbqCKHeh3PAVTr5hA/biLE9yICtopU5uuaEQVT9qE4jIBDQeSGOOoS3n9dvUNlDjTu64kvEx5bjju47wlE7+mUOnb4qFht4otLDcaHmzX4H19WWxI7PSmsJZV6/MJ7j932eVi26YGVI3Ucu8ivdI=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      condition: -e DEPLOY_WET
