# deploy to test PyPI. tests the same as the build workflow but also deploys.
name: test_deploy

on: workflow_dispatch

env:
  # where to mount the top-level directory of the repo in docker
  DOCKER_MNT: /_build

jobs:
  test_deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Download .tar.gz and manylinux wheel artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist_artifact
        path: dist
    - name: Deploy manylinux1 wheels and tar.gz source to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.LOCAL_TESTPYPI_TOKEN}}
        repository_url: https://test.pypi.org/legacy/
        # keep uploading tar.gz source since this is a matrix job
        skip_existing: true