# deploy to test PyPI. use artifacts uploaded by build.yaml for distribution.
# since we can't use download-artifact across workflows, we use the REST API.
name: test_deploy

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Download .tar.gz and manylinux wheel artifacts
      run: >
        python3 tools/download_artifact.py $GITHUB_REPOSITORY -n dist_artifact
        -d dist -u
    - name: Deploy manylinux wheels and tar.gz source to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.LOCAL_TESTPYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/