# deploy to test PyPI. use artifacts uploaded by build.yaml for distribution.
name: test_deploy

on: workflow_dispatch

jobs:
  test_deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Download .tar.gz and manylinux wheel artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist_artifact
        path: dist
    - name: Deploy manylinux wheels and tar.gz source to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.LOCAL_TESTPYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/